name: Build, Test and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Maven Dependencies
        run: mvn -B dependency:resolve

      - name: Run Tests and static analysis
        run: mvn -B -DskipTests=false clean verify checkstyle:check spotbugs:check

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push GHCR
        id: build
        run: |
          # Make owner lowercase (shell-side), because GitHub expression lowercase isn't supported
          OWNER="${{ github.repository_owner }}"
          OWNER="$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')"
          IMAGE=ghcr.io/$OWNER/similar-product
          TAG=${{ github.sha }}
          
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG
          
          echo "image=$IMAGE:$TAG" >> $GITHUB_OUTPUT

      - name: Set output image
        id: set-image
        run: |
          OWNER="${{ github.repository_owner }}"
          OWNER="$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')"
          echo "image=ghcr.io/$OWNER/similar-product:${{ github.sha }}" >> $GITHUB_OUTPUT


  smoke:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Pull and run image
        run: |
          docker pull ${{ needs.build-and-push.outputs.image }}
          docker run -d --name app -p 5000:5000 ${{ needs.build-and-push.outputs.image }}
          sleep 8

      - name: Health check
        run: curl -f http://localhost:5000/actuator/health
